language: go

os:
- linux
- osx

go:
- "1.16"

git:
  depth: 1

go_import_path: sigs.k8s.io/cli-experimental

install:
- go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.23.8

script:
- TRACE=1 ./scripts/check-everything.sh

# TBD. Suppressing for now.
notifications:
  email: false